### PR TITLE
fix: Bump API version and fix for EW.

### PR DESCRIPTION
**Pull request by unixtreme**
Resolves: #4

### CODE REVIEW

**Comment by Aida-Enna** [comment]
This does indeed fix it, working as intended. 👍

**Comment by NaesKun** [comment]
How do I apply this fix?

**Comment by Xorag** [comment]
> How do I apply this fix?

you'd have to install visual studio and follow some steps in the quicklauncher FAQ to build the DLL and replace them on your system - I did this and its working for me as well :)

**Review by nullfact0r — APPROVED** [review]

**Comment by Zaphod392** [comment]
Any way to have a download or the patch applied? :) dont have VS :)

**Comment by Aida-Enna** [comment]
[FPSPlugin.zip](https://github.com/Caraxi/FPSPlugin/files/7775900/FPSPlugin.zip)

Here is a prebuilt version with the fix - As always, when downloading something from someone you don't know, please run this file through your antivirus and/or virustotal.com.

**Comment by Zaphod392** [comment]
Thank you so much! I also agree, always run scans on everything!

**Comment by xPumaa** [comment]
@unixtreme @Caraxi the address for the windowsInactive variable should be 17D0

**Comment by Xorag** [comment]
> @unixtreme @Caraxi the address for the windowsInactive variable should be 17D0

i recompiled with this change and used it all day yesterday. no issues or crashes but seemingly no other changes/improvments, so im curious what it does?

**Comment by xPumaa** [comment]
@Xorag this is used to store the current fps only in history when the game is active. The history is needed for calculating the average fps. At least that's how I understood it.

**Pull request merged**
